// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIUserValidation.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20241001021245_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.ClientME", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClientLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GenreIdIdentificationId")
                        .HasColumnType("int");

                    b.Property<int?>("IdentificationId")
                        .HasColumnType("int");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelatIdRelationId")
                        .HasColumnType("int");

                    b.Property<int?>("RolID")
                        .HasColumnType("int");

                    b.Property<int>("UsuId")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.HasIndex("GenreIdIdentificationId");

                    b.HasIndex("IdentificationId");

                    b.HasIndex("RelatIdRelationId");

                    b.HasIndex("RolID");

                    b.ToTable("ClientME", "UVA");
                });

            modelBuilder.Entity("Models.GenreME", b =>
                {
                    b.Property<int>("IdentificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentificationId"));

                    b.Property<string>("IdentificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdentificationId");

                    b.ToTable("GenreME", "UVA");
                });

            modelBuilder.Entity("Models.IdClientME", b =>
                {
                    b.Property<int>("IdentyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentyId"));

                    b.Property<string>("IdentiType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdentyId");

                    b.ToTable("IdClientME", "UVA");
                });

            modelBuilder.Entity("Models.IdentificationME", b =>
                {
                    b.Property<int>("IdentificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentificationId"));

                    b.Property<string>("IdentificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdentificationId");

                    b.ToTable("IdentificationME", "UVA");
                });

            modelBuilder.Entity("Models.RelationShME", b =>
                {
                    b.Property<int>("RelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelationId"));

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RelationId");

                    b.ToTable("RelationShME", "UVA");
                });

            modelBuilder.Entity("Models.RoleME", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolID"));

                    b.Property<string>("RolType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RolID");

                    b.ToTable("RoleME", "UVA");
                });

            modelBuilder.Entity("Models.UserInfoME", b =>
                {
                    b.Property<int>("UsuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuId"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("UsuClientClientId")
                        .HasColumnType("int");

                    b.HasKey("UsuId");

                    b.HasIndex("UsuClientClientId");

                    b.ToTable("UserInfo", "UVA");
                });

            modelBuilder.Entity("Models.ClientME", b =>
                {
                    b.HasOne("Models.GenreME", "GenreId")
                        .WithMany()
                        .HasForeignKey("GenreIdIdentificationId");

                    b.HasOne("Models.IdentificationME", "Identification")
                        .WithMany()
                        .HasForeignKey("IdentificationId");

                    b.HasOne("Models.RelationShME", "RelatId")
                        .WithMany()
                        .HasForeignKey("RelatIdRelationId");

                    b.HasOne("Models.RoleME", "RolId")
                        .WithMany()
                        .HasForeignKey("RolID");

                    b.Navigation("GenreId");

                    b.Navigation("Identification");

                    b.Navigation("RelatId");

                    b.Navigation("RolId");
                });

            modelBuilder.Entity("Models.UserInfoME", b =>
                {
                    b.HasOne("Models.ClientME", "UsuClient")
                        .WithMany()
                        .HasForeignKey("UsuClientClientId");

                    b.Navigation("UsuClient");
                });
#pragma warning restore 612, 618
        }
    }
}
