// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIUserValidation.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20250130154404_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("UVA")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiUserValidation.Models.Entities.PersonME", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClientId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Age");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2")
                        .HasColumnName("Birthday");

                    b.Property<string>("ClientLastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClientLastName");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClientName");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("Gender");

                    b.Property<int?>("IdentificationId")
                        .HasColumnType("int")
                        .HasColumnName("IdentificationId");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IdentificationNumber");

                    b.Property<int>("UsuId")
                        .HasColumnType("int")
                        .HasColumnName("UsuId");

                    b.HasKey("PersonId");

                    b.HasIndex("GenderId");

                    b.HasIndex("IdentificationId");

                    b.ToTable("PersonME", "UVA");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserAttributesME.GenderME", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GenderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"));

                    b.Property<string>("GenderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("GenderType");

                    b.HasKey("GenderId");

                    b.ToTable("GenderME", "UVA");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserAttributesME.IdentificationME", b =>
                {
                    b.Property<int>("IdentificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdentificationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentificationId"));

                    b.Property<string>("IdentificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdentificationId");

                    b.ToTable("IdentificationME", "UVA");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserAttributesME.RelationShME", b =>
                {
                    b.Property<int>("RelatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RelatId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelatId"));

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("RelationType");

                    b.HasKey("RelatId");

                    b.ToTable("RelationShME", "UVA");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserAttributesME.RoleME", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolID"));

                    b.Property<string>("RolType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("RolType");

                    b.HasKey("RolID");

                    b.ToTable("RoleME", "UVA");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserAttributesME.StatusME", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StatusId");

                    b.ToTable("StatusME", "UVA");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserInfoME", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastLogin");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("PersonId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("UserName");

                    b.Property<string>("UserPasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("UserPasswordHash");

                    b.HasKey("UserId");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasFilter("[PersonId] IS NOT NULL");

                    b.ToTable("UserInfo", "UVA");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.ClientME", b =>
                {
                    b.HasBaseType("ApiUserValidation.Models.Entities.PersonME");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RolId");

                    b.Property<int?>("UserInfoId")
                        .HasColumnType("int")
                        .HasColumnName("UsuId");

                    b.HasIndex("RoleId");

                    b.ToTable("ClientME", "UVA");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.PersonME", b =>
                {
                    b.HasOne("ApiUserValidation.Models.Entities.UserAttributesME.GenderME", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("ApiUserValidation.Models.Entities.UserAttributesME.IdentificationME", "Identification")
                        .WithMany()
                        .HasForeignKey("IdentificationId");

                    b.Navigation("Gender");

                    b.Navigation("Identification");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserInfoME", b =>
                {
                    b.HasOne("ApiUserValidation.Models.Entities.PersonME", "Person")
                        .WithOne("UserInfo")
                        .HasForeignKey("ApiUserValidation.Models.Entities.UserInfoME", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.ClientME", b =>
                {
                    b.HasOne("ApiUserValidation.Models.Entities.PersonME", null)
                        .WithOne()
                        .HasForeignKey("ApiUserValidation.Models.Entities.ClientME", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiUserValidation.Models.Entities.UserAttributesME.RoleME", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.PersonME", b =>
                {
                    b.Navigation("UserInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
