// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIUserValidation.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20250129220110_RenameGenderTableAndColumn")]
    partial class RenameGenderTableAndColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserAttributes.GenderME", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GenderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"));

                    b.Property<string>("GenderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("GenderType");

                    b.HasKey("GenderId");

                    b.ToTable("GenderME", "UVA");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserAttributes.IdentificationME", b =>
                {
                    b.Property<int>("IdentificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdentificationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentificationId"));

                    b.Property<string>("IdentificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdentificationId");

                    b.ToTable("IdentificationME", "UVA");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserAttributes.RelationShME", b =>
                {
                    b.Property<int>("RelatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RelatId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelatId"));

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("RelationType");

                    b.HasKey("RelatId");

                    b.ToTable("RelationShME", "UVA");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserAttributes.RoleME", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolID"));

                    b.Property<string>("RolType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("RolType");

                    b.HasKey("RolID");

                    b.ToTable("RoleME", "UVA");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserInfoME", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("UserName");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("UserPassword");

                    b.HasKey("UserName");

                    b.ToTable("UserInfo", "UVA");
                });

            modelBuilder.Entity("ClientME", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClientId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Age");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2")
                        .HasColumnName("Birthday");

                    b.Property<string>("ClientLastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClientLastName");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClientName");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("Gender");

                    b.Property<int?>("IdentificationId")
                        .HasColumnType("int")
                        .HasColumnName("IdentificationId");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IdentificationNumber");

                    b.Property<int?>("RelatId")
                        .HasColumnType("int")
                        .HasColumnName("RelatId");

                    b.Property<int?>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolId");

                    b.Property<int>("UsuId")
                        .HasColumnType("int")
                        .HasColumnName("UsuId");

                    b.HasKey("ClientId");

                    b.HasIndex("GenderId");

                    b.HasIndex("IdentificationId");

                    b.HasIndex("RelatId");

                    b.HasIndex("RolId");

                    b.ToTable("ClientME", "UVA");
                });

            modelBuilder.Entity("ClientME", b =>
                {
                    b.HasOne("ApiUserValidation.Models.Entities.UserAttributes.GenderME", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("ApiUserValidation.Models.Entities.UserAttributes.IdentificationME", "Identification")
                        .WithMany()
                        .HasForeignKey("IdentificationId");

                    b.HasOne("ApiUserValidation.Models.Entities.UserAttributes.RelationShME", "Relation")
                        .WithMany()
                        .HasForeignKey("RelatId");

                    b.HasOne("ApiUserValidation.Models.Entities.UserAttributes.RoleME", "Role")
                        .WithMany()
                        .HasForeignKey("RolId");

                    b.Navigation("Gender");

                    b.Navigation("Identification");

                    b.Navigation("Relation");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
