// <auto-generated />
using System;
using ApiUserValidation.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIUserValidation.Migrations
{
    [DbContext(typeof(WebAppDbContext))]
    [Migration("20250205021247_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("UVA")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiUserValidation.Models.Entities.PersonME", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PersonId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Age");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2")
                        .HasColumnName("Birthday");

                    b.Property<string>("ClientLastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClientLastName");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClientName");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("GenderId");

                    b.Property<int?>("IdentificationId")
                        .HasColumnType("int")
                        .HasColumnName("IdentificationId");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IdentificationNumber");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Phone");

                    b.Property<int?>("UserInfoPersonId")
                        .HasColumnType("int");

                    b.HasKey("PersonId");

                    b.HasIndex("GenderId");

                    b.HasIndex("IdentificationId");

                    b.HasIndex("UserInfoPersonId");

                    b.ToTable("PersonME", "UVA");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserAttributesME.GenderME", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GenderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"));

                    b.Property<string>("GenderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("GenderType");

                    b.HasKey("GenderId");

                    b.ToTable("GenderME", "UVA");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserAttributesME.IdentificationME", b =>
                {
                    b.Property<int>("IdentificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdentificationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentificationId"));

                    b.Property<string>("IdentificationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdentificationId");

                    b.ToTable("IdentificationME", "UVA");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserAttributesME.RoleME", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolID"));

                    b.Property<string>("RolType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("RolType");

                    b.HasKey("RolID");

                    b.ToTable("RoleME", "UVA");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserAttributesME.StatusME", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StatusId");

                    b.ToTable("StatusME", "UVA");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserME", b =>
                {
                    b.HasBaseType("ApiUserValidation.Models.Entities.PersonME");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastLogin");

                    b.Property<int?>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolId");

                    b.Property<int?>("RoleRolID")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("UserName");

                    b.Property<string>("UserPasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("UserPasswordHash");

                    b.HasIndex("RoleRolID");

                    b.HasIndex("StatusId");

                    b.ToTable("UserME", "UVA");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.PersonME", b =>
                {
                    b.HasOne("ApiUserValidation.Models.Entities.UserAttributesME.GenderME", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("ApiUserValidation.Models.Entities.UserAttributesME.IdentificationME", "Identification")
                        .WithMany()
                        .HasForeignKey("IdentificationId");

                    b.HasOne("ApiUserValidation.Models.Entities.UserME", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserInfoPersonId");

                    b.Navigation("Gender");

                    b.Navigation("Identification");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("ApiUserValidation.Models.Entities.UserME", b =>
                {
                    b.HasOne("ApiUserValidation.Models.Entities.PersonME", null)
                        .WithOne()
                        .HasForeignKey("ApiUserValidation.Models.Entities.UserME", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiUserValidation.Models.Entities.UserAttributesME.RoleME", "Role")
                        .WithMany()
                        .HasForeignKey("RoleRolID");

                    b.HasOne("ApiUserValidation.Models.Entities.UserAttributesME.StatusME", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
